
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 24 21:25:48 GMT-03:00 2016
//----------------------------------------------------

package compiler.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTO = 13; //ok
  public static final int DIFERENTE_QUE = 4; // ok
  public static final int KEY_CHAR = 33;  // ok
  public static final int MULT = 11; // ok
  public static final int CHAR_LITERAL = 26; // ok
  public static final int SOMA = 9; // ok
  public static final int ABRE_CHAVE = 22; //ok
  public static final int FECHA_CHAVE = 23; //ok
  public static final int VIRGULA = 18; // ok
  public static final int IDENTIFICADOR = 2; // ok
  public static final int MENOR_OU_IGUAL = 8; // ok
  public static final int NOT = 16; //ok
  public static final int AND = 14; //ok
  public static final int ABRE_PAR = 20; // ok
  public static final int OR = 15; // ok
  public static final int KEY_WHILE = 29; // ok
  public static final int KEY_VAR = 35; // ok
  public static final int KEY_FLOAT = 32; // ok
  public static final int DIV = 12;
  public static final int FECHA_PAR = 21; // ok
  public static final int EOF = 0; // ok
  public static final int PONTO_VIRGULA = 19; // ok
  public static final int error = 1;
  public static final int KEY_PRINT = 34; // ok
  public static final int MAIOR_QUE = 5; // ok
  public static final int KEY_INT = 31; // ok
  public static final int KEY_RETURN = 30; // ok
  public static final int KEY_ELSE = 28; // ok
  public static final int IGUAL_QUE = 3; // ok
  public static final int MAIOR_OU_IGUAL = 7; // ok
  public static final int KEY_IF = 27; // ok
  public static final int KEY_PROC = 36; // ok
  public static final int ATRIBUICAO = 17; // ok
  public static final int MENOR_QUE = 6; // ok
  public static final int FLOAT_LITERAL = 25; // ok
  public static final int SUB = 10; // ok
  public static final int INT_LITERAL = 24; // ok
}

